name: dsml-kit

services:
  app:
    image: ghcr.io/mihneateodorstoica/dsml-kit:latest
    container_name: dsml
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]