from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any
import tomllib
import re

import yaml

from dsml import tokens


class ConfigError(ValueError):
    pass


class _IndentedDumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        return super().increase_indent(flow, False)


DEFAULT_CONFIG: dict[str, Any] = {
    "runtime": {
        "backend": "compose",
    },
    "workspace": {
        "profile": "minimal",
        "mount": "./workspace",
        "port": 8888,
        "bind_address": "127.0.0.1",
        "container_name": "auto",
        "home_volume": "auto",
        "gpu": "auto",
        "image": "ghcr.io/mihneateodorstoica/dsml-kit:minimal",
        "image_policy": "auto",
        "jupyter_token": "auto",
    },
    "image_build": {
        "context": ".",
        "dockerfile": "images/base/Dockerfile",
        "target": "",
        "args": {
            "PYTHON_VERSION": "3.11",
            "DSML_REQUIREMENTS": "requirements-minimal.txt",
        },
        "watch": ["images/base", ".dockerignore"],
    },
    "jupyter": {
        "root_dir": "/home/jovyan/work",
        "base_url": "/",
        "app_log_level": "WARN",
        "server_log_level": "WARN",
        "extra_args": [],
    },
    "packages": {
        "extra": [],
    },
}


def default_config(
    *,
    profile: str = "minimal",
    port: int = 8888,
    gpu: bool | str = "auto",
    image: str | None = None,
) -> dict[str, Any]:
    data = deepcopy(DEFAULT_CONFIG)
    data["workspace"]["profile"] = profile
    data["workspace"]["port"] = port
    data["workspace"]["gpu"] = gpu
    if image is not None:
        data["workspace"]["image"] = image
    return data


def merge_defaults(data: dict[str, Any]) -> dict[str, Any]:
    merged = deepcopy(DEFAULT_CONFIG)
    for section, values in data.items():
        if isinstance(values, dict) and isinstance(merged.get(section), dict):
            merged[section].update(values)
        else:
            merged[section] = values
    return merged


def read_config(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise ConfigError(f"Config file not found: {path}")
    try:
        if path.suffix.lower() in {".yml", ".yaml"}:
            loaded = yaml.safe_load(path.read_text()) or {}
        else:
            loaded = tomllib.loads(path.read_text())
    except tomllib.TOMLDecodeError as exc:
        raise ConfigError(f"Invalid TOML in {path}: {exc}") from exc
    except yaml.YAMLError as exc:
        raise ConfigError(f"Invalid YAML in {path}: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ConfigError(f"Config file must contain a mapping: {path}")
    data = dict(loaded)
    return validate_config(merge_defaults(data))


def write_config(
    path: Path,
    data: dict[str, Any],
    *,
    overwrite: bool = False,
    documented: bool = False,
) -> None:
    if path.exists() and not overwrite:
        raise ConfigError(f"{path.name} already exists. Use --force to overwrite it.")
    if path.suffix.lower() not in {".yml", ".yaml"}:
        raise ConfigError("New workspace configuration must be written as dsml.yml.")
    validated = validate_config(merge_defaults(data))
    path.write_text(render_documented_config(validated) if documented else render_config(validated))


def render_config(data: dict[str, Any]) -> str:
    validated = validate_config(merge_defaults(data))
    return yaml.dump(validated, Dumper=_IndentedDumper, sort_keys=False, default_flow_style=False)


def render_documented_config(data: dict[str, Any]) -> str:
    validated = validate_config(merge_defaults(data))
    workspace = validated["workspace"]
    image_build = validated["image_build"]
    runtime = validated["runtime"]
    jupyter = validated["jupyter"]
    packages = validated["packages"]

    lines = [
        "# Workspace-local dsml configuration generated by `dsml init`.",
        "# Edit this file directly, or use commands such as `dsml add`.",
        "",
        "runtime:",
        "  # Workspace runtime backend. Compose is generated from this file.",
        _entry("backend", runtime["backend"], indent=2),
        "",
        "workspace:",
        "  # Bundled profile name from profiles/*.yml: minimal, base, extended, full, gpu, or dev.",
        _entry("profile", workspace["profile"], indent=2),
        "  # Host path mounted into the container, relative to this dsml.yml.",
        _entry("mount", workspace["mount"], indent=2),
        "  # Host address and port mapped to Jupyter inside the container.",
        _entry("port", workspace["port"], indent=2),
        _entry("bind_address", workspace["bind_address"], indent=2),
        "  # Docker container name and persistent /home/jovyan volume.",
        "  # Use auto to derive stable names from the project path.",
        _entry("container_name", workspace["container_name"], indent=2),
        _entry("home_volume", workspace["home_volume"], indent=2),
        "  # GPU mode: auto, true, or false.",
        _entry("gpu", workspace["gpu"], indent=2),
        "  # Runtime Docker image used by `dsml up`.",
        _entry("image", workspace["image"], indent=2),
        "  # Image preparation policy for `dsml up`: auto, pull, build, or never.",
        _entry("image_policy", workspace["image_policy"], indent=2),
        "  # Jupyter token, or auto to generate one each time the workspace starts.",
        _entry("jupyter_token", workspace["jupyter_token"], indent=2),
        "",
        "image_build:",
        "  # Used when image_policy is build, or when `dsml up --build` is passed.",
        "  # context and watch paths are relative to this dsml.yml; dockerfile is relative to context.",
        _entry("context", image_build["context"], indent=2),
        _entry("dockerfile", image_build["dockerfile"], indent=2),
        "  # Optional Dockerfile stage target and Docker build args.",
        _entry("target", image_build["target"], indent=2),
        _entry("args", image_build["args"], indent=2),
        "  # Paths watched by `dsml watch`.",
        _entry("watch", image_build["watch"], indent=2),
        "",
        "jupyter:",
        "  # Container path Jupyter opens. The project mount usually lives at /home/jovyan/work.",
        _entry("root_dir", jupyter["root_dir"], indent=2),
        "  # URL prefix and Jupyter log levels.",
        _entry("base_url", jupyter["base_url"], indent=2),
        _entry("app_log_level", jupyter["app_log_level"], indent=2),
        _entry("server_log_level", jupyter["server_log_level"], indent=2),
        "  # Additional start-notebook.py arguments.",
        _entry("extra_args", jupyter["extra_args"], indent=2),
        "",
        "packages:",
        "  # Project-specific packages installed by `dsml add` or `dsml sync`.",
        "  # Reusable image dependencies belong in images/base/requirements-*.txt.",
        _entry("extra", packages["extra"], indent=2),
    ]
    return "\n".join(lines) + "\n"


def validate_config(data: dict[str, Any]) -> dict[str, Any]:
    for section in ("runtime", "workspace", "image_build", "jupyter", "packages"):
        if not isinstance(data.get(section), dict):
            raise ConfigError(f"Missing or invalid {section} section.")

    runtime = data["runtime"]
    workspace = data["workspace"]
    image_build = data["image_build"]
    jupyter = data["jupyter"]
    packages = data["packages"]

    runtime["backend"] = _valid_runtime_backend(runtime.get("backend", "compose"))

    workspace["profile"] = _required_string(workspace, "profile")
    workspace["mount"] = _required_string(workspace, "mount")
    workspace["bind_address"] = _valid_bind_address(workspace.get("bind_address"))
    workspace["container_name"] = _required_string(workspace, "container_name")
    workspace["home_volume"] = _required_string(workspace, "home_volume")
    workspace["image"] = _required_string(workspace, "image")
    workspace["image_policy"] = _valid_image_policy(workspace.get("image_policy", "auto"))
    workspace["jupyter_token"] = str(workspace.get("jupyter_token", "auto")).strip() or "auto"
    workspace["port"] = _valid_port(workspace.get("port"))
    workspace["gpu"] = _valid_gpu(workspace.get("gpu", "auto"))

    image_build["context"] = _required_string(image_build, "context")
    image_build["dockerfile"] = _required_string(image_build, "dockerfile")
    image_build["target"] = str(image_build.get("target", "")).strip()
    if not isinstance(image_build.get("args"), dict):
        raise ConfigError("image_build.args must be a mapping.")
    image_build["args"] = _valid_image_build_args({
        str(key): str(value)
        for key, value in image_build["args"].items()
        if str(key).strip()
    })
    if not isinstance(image_build.get("watch"), list):
        raise ConfigError("image_build.watch must be a list.")
    image_build["watch"] = [str(path) for path in image_build["watch"]]

    jupyter["root_dir"] = _required_string(jupyter, "root_dir")
    jupyter["base_url"] = _required_string(jupyter, "base_url")
    jupyter["app_log_level"] = _required_string(jupyter, "app_log_level")
    jupyter["server_log_level"] = _required_string(jupyter, "server_log_level")
    if not isinstance(jupyter.get("extra_args"), list):
        raise ConfigError("[jupyter].extra_args must be a list.")
    jupyter["extra_args"] = [str(arg) for arg in jupyter["extra_args"]]

    if not isinstance(packages.get("extra"), list):
        raise ConfigError("[packages].extra must be a list.")
    packages["extra"] = [str(package) for package in packages["extra"]]

    return data


def create_project_config(
    *,
    profile: str,
    profile_image: str,
    profile_image_build: dict[str, Any] | None = None,
    port: int,
    gpu: bool | str,
    image: str | None,
) -> dict[str, Any]:
    data = default_config(
        profile=profile,
        port=port,
        gpu=gpu,
        image=image or profile_image,
    )
    if profile_image_build:
        data["image_build"] = merge_defaults({"image_build": profile_image_build})["image_build"]
    return data


def add_packages(path: Path, packages: list[str]) -> dict[str, Any]:
    data = read_config(path)
    current = data["packages"]["extra"]
    for package in packages:
        if package not in current:
            current.append(package)
    write_config(path, data, overwrite=True)
    return data


def read_requirement_specs(paths: list[Path]) -> list[str]:
    specs: list[str] = []
    seen_files: set[Path] = set()
    for path in paths:
        specs.extend(_read_requirement_specs(path, seen_files=seen_files))
    return _dedupe(specs)


def resolve_token(data: dict[str, Any]) -> str:
    return tokens.normalize_token(data["workspace"].get("jupyter_token"))


def _required_string(data: dict[str, Any], key: str) -> str:
    value = str(data.get(key, "")).strip()
    if not value:
        raise ConfigError(f"Missing required config value: {key}")
    return value


def _valid_port(value: object) -> int:
    if isinstance(value, bool):
        raise ConfigError("[workspace].port must be an integer.")
    if isinstance(value, int):
        port = value
    elif isinstance(value, str):
        try:
            port = int(value.strip())
        except ValueError as exc:
            raise ConfigError("[workspace].port must be an integer.") from exc
    else:
        raise ConfigError("[workspace].port must be an integer.")
    if port < 1 or port > 65535:
        raise ConfigError("[workspace].port must be between 1 and 65535.")
    return port


def _valid_bind_address(value: object) -> str:
    text = _required_string({"bind_address": value}, "bind_address")
    if text in {"0.0.0.0", "::", "[::]"}:
        raise ConfigError("[workspace].bind_address must target a specific host interface, not all interfaces.")
    return text


def _valid_gpu(value: object) -> bool | str:
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    if text == "auto":
        return "auto"
    if text == "true":
        return True
    if text == "false":
        return False
    raise ConfigError("[workspace].gpu must be one of: auto, true, false.")


def _valid_image_policy(value: object) -> str:
    text = str(value or "auto").strip().lower()
    if text in {"auto", "pull", "build", "never"}:
        return text
    raise ConfigError("[workspace].image_policy must be one of: auto, pull, build, never.")


def _valid_runtime_backend(value: object) -> str:
    text = str(value or "compose").strip().lower()
    if text == "compose":
        return text
    raise ConfigError("[runtime].backend must be 'compose'.")


def _valid_image_build_args(args: dict[str, str]) -> dict[str, str]:
    requirements = args.get("DSML_REQUIREMENTS")
    if requirements is not None:
        if "/" in requirements or "\\" in requirements or requirements.startswith("."):
            raise ConfigError("image_build.args.DSML_REQUIREMENTS must be a file name, not a path.")
        if not requirements.startswith("requirements-") or not requirements.endswith(".txt"):
            raise ConfigError("image_build.args.DSML_REQUIREMENTS must look like requirements-<variant>.txt.")
    python_version = args.get("PYTHON_VERSION")
    if python_version is not None and python_version not in {"3.10", "3.11", "3.12"}:
        raise ConfigError("image_build.args.PYTHON_VERSION must be one of: 3.10, 3.11, 3.12.")
    apt_packages = args.get("DSML_EXTRA_APT_PACKAGES")
    if apt_packages is not None and not re.fullmatch(r"[A-Za-z0-9+_.: -]*", apt_packages):
        raise ConfigError("image_build.args.DSML_EXTRA_APT_PACKAGES contains unsupported characters.")
    return args


def _entry(key: str, value: object, *, indent: int = 0) -> str:
    dumped = yaml.dump({key: value}, Dumper=_IndentedDumper, sort_keys=False, default_flow_style=False).rstrip()
    prefix = " " * indent
    return "\n".join(f"{prefix}{line}" for line in dumped.splitlines())


def _read_requirement_specs(path: Path, *, seen_files: set[Path]) -> list[str]:
    resolved = path.expanduser().resolve()
    if resolved in seen_files:
        return []
    seen_files.add(resolved)
    if not resolved.is_file():
        raise ConfigError(f"Requirements file not found: {path}")

    specs: list[str] = []
    for line_number, raw_line in enumerate(resolved.read_text().splitlines(), start=1):
        line = _strip_requirement_comment(raw_line).strip()
        if not line:
            continue
        if line.startswith("-r ") or line.startswith("--requirement "):
            nested = line.split(maxsplit=1)[1]
            specs.extend(_read_requirement_specs(resolved.parent / nested, seen_files=seen_files))
            continue
        if line.startswith("-"):
            raise ConfigError(
                f"Unsupported requirements option in {resolved}:{line_number}: {line}. "
                "Only package specifiers and nested -r files can be added to dsml.yml."
            )
        specs.append(line)
    return specs


def _strip_requirement_comment(line: str) -> str:
    stripped = line.lstrip()
    if stripped.startswith("#"):
        return ""
    for marker in (" #", "\t#"):
        index = line.find(marker)
        if index != -1:
            return line[:index]
    return line


def _dedupe(values: list[str]) -> list[str]:
    deduped: list[str] = []
    for value in values:
        if value not in deduped:
            deduped.append(value)
    return deduped
