from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any
import tomllib

import tomli_w

from dsml import tokens


class ConfigError(ValueError):
    pass


DEFAULT_CONFIG: dict[str, Any] = {
    "workspace": {
        "profile": "minimal",
        "mount": "./workspace",
        "port": 8888,
        "bind_address": "127.0.0.1",
        "container_name": "auto",
        "home_volume": "auto",
        "gpu": "auto",
        "image": "ghcr.io/mihneateodorstoica/dsml-kit:minimal",
        "jupyter_token": "auto",
    },
    "jupyter": {
        "root_dir": "/home/jovyan/work",
        "base_url": "/",
        "app_log_level": "WARN",
        "server_log_level": "WARN",
        "extra_args": [],
    },
    "packages": {
        "extra": [],
    },
}


def default_config(
    *,
    profile: str = "minimal",
    port: int = 8888,
    gpu: bool | str = "auto",
    image: str | None = None,
) -> dict[str, Any]:
    data = deepcopy(DEFAULT_CONFIG)
    data["workspace"]["profile"] = profile
    data["workspace"]["port"] = port
    data["workspace"]["gpu"] = gpu
    if image is not None:
        data["workspace"]["image"] = image
    return data


def merge_defaults(data: dict[str, Any]) -> dict[str, Any]:
    merged = deepcopy(DEFAULT_CONFIG)
    for section, values in data.items():
        if isinstance(values, dict) and isinstance(merged.get(section), dict):
            merged[section].update(values)
        else:
            merged[section] = values
    return merged


def read_config(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise ConfigError(f"Config file not found: {path}")
    try:
        data = tomllib.loads(path.read_text())
    except tomllib.TOMLDecodeError as exc:
        raise ConfigError(f"Invalid TOML in {path}: {exc}") from exc
    return validate_config(merge_defaults(data))


def write_config(
    path: Path,
    data: dict[str, Any],
    *,
    overwrite: bool = False,
    documented: bool = False,
) -> None:
    if path.exists() and not overwrite:
        raise ConfigError(f"{path.name} already exists. Use --force to overwrite it.")
    validated = validate_config(merge_defaults(data))
    path.write_text(render_documented_config(validated) if documented else tomli_w.dumps(validated))


def render_documented_config(data: dict[str, Any]) -> str:
    validated = validate_config(merge_defaults(data))
    workspace = validated["workspace"]
    jupyter = validated["jupyter"]
    packages = validated["packages"]

    lines = [
        "# Workspace-local dsml configuration generated by `dsml init`.",
        "# Edit this file directly, or use commands such as `dsml add`.",
        "",
        "[workspace]",
        "# Bundled profile name from profiles/*.toml: minimal, gpu, full, or dev.",
        _entry("profile", workspace["profile"]),
        "# Host path mounted into the container, relative to this dsml.toml.",
        _entry("mount", workspace["mount"]),
        "# Host address and port mapped to Jupyter inside the container.",
        _entry("port", workspace["port"]),
        _entry("bind_address", workspace["bind_address"]),
        "# Docker container name and persistent /home/jovyan volume.",
        "# Use auto to derive stable names from the project path.",
        _entry("container_name", workspace["container_name"]),
        _entry("home_volume", workspace["home_volume"]),
        "# GPU mode: auto, true, or false.",
        _entry("gpu", workspace["gpu"]),
        "# Runtime Docker image used by `dsml up`.",
        _entry("image", workspace["image"]),
        "# Jupyter token, or auto to generate one each time the workspace starts.",
        _entry("jupyter_token", workspace["jupyter_token"]),
        "",
        "[jupyter]",
        "# Container path Jupyter opens. The project mount usually lives at /home/jovyan/work.",
        _entry("root_dir", jupyter["root_dir"]),
        "# URL prefix and Jupyter log levels.",
        _entry("base_url", jupyter["base_url"]),
        _entry("app_log_level", jupyter["app_log_level"]),
        _entry("server_log_level", jupyter["server_log_level"]),
        "# Additional start-notebook.py arguments.",
        _entry("extra_args", jupyter["extra_args"]),
        "",
        "[packages]",
        "# Project-specific packages installed by `dsml add` or `dsml sync`.",
        "# Reusable image dependencies belong in images/base/requirements.txt.",
        _entry("extra", packages["extra"]),
    ]
    return "\n".join(lines) + "\n"


def validate_config(data: dict[str, Any]) -> dict[str, Any]:
    for section in ("workspace", "jupyter", "packages"):
        if not isinstance(data.get(section), dict):
            raise ConfigError(f"Missing or invalid [{section}] section.")

    workspace = data["workspace"]
    jupyter = data["jupyter"]
    packages = data["packages"]

    workspace["profile"] = _required_string(workspace, "profile")
    workspace["mount"] = _required_string(workspace, "mount")
    workspace["bind_address"] = _required_string(workspace, "bind_address")
    workspace["container_name"] = _required_string(workspace, "container_name")
    workspace["home_volume"] = _required_string(workspace, "home_volume")
    workspace["image"] = _required_string(workspace, "image")
    workspace["jupyter_token"] = str(workspace.get("jupyter_token", "auto")).strip() or "auto"
    workspace["port"] = _valid_port(workspace.get("port"))
    workspace["gpu"] = _valid_gpu(workspace.get("gpu", "auto"))

    jupyter["root_dir"] = _required_string(jupyter, "root_dir")
    jupyter["base_url"] = _required_string(jupyter, "base_url")
    jupyter["app_log_level"] = _required_string(jupyter, "app_log_level")
    jupyter["server_log_level"] = _required_string(jupyter, "server_log_level")
    if not isinstance(jupyter.get("extra_args"), list):
        raise ConfigError("[jupyter].extra_args must be a list.")
    jupyter["extra_args"] = [str(arg) for arg in jupyter["extra_args"]]

    if not isinstance(packages.get("extra"), list):
        raise ConfigError("[packages].extra must be a list.")
    packages["extra"] = [str(package) for package in packages["extra"]]

    return data


def create_project_config(
    *,
    profile: str,
    profile_image: str,
    port: int,
    gpu: bool | str,
    image: str | None,
) -> dict[str, Any]:
    return default_config(
        profile=profile,
        port=port,
        gpu=gpu,
        image=image or profile_image,
    )


def add_packages(path: Path, packages: list[str]) -> dict[str, Any]:
    data = read_config(path)
    current = data["packages"]["extra"]
    for package in packages:
        if package not in current:
            current.append(package)
    write_config(path, data, overwrite=True)
    return data


def resolve_token(data: dict[str, Any]) -> str:
    return tokens.normalize_token(data["workspace"].get("jupyter_token"))


def _required_string(data: dict[str, Any], key: str) -> str:
    value = str(data.get(key, "")).strip()
    if not value:
        raise ConfigError(f"Missing required config value: {key}")
    return value


def _valid_port(value: object) -> int:
    try:
        port = int(value)
    except (TypeError, ValueError) as exc:
        raise ConfigError("[workspace].port must be an integer.") from exc
    if port < 1 or port > 65535:
        raise ConfigError("[workspace].port must be between 1 and 65535.")
    return port


def _valid_gpu(value: object) -> bool | str:
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    if text == "auto":
        return "auto"
    if text == "true":
        return True
    if text == "false":
        return False
    raise ConfigError("[workspace].gpu must be one of: auto, true, false.")


def _entry(key: str, value: object) -> str:
    return tomli_w.dumps({key: value}).strip()
