from pathlib import Path

from typer.testing import CliRunner

from dsml import cli
from dsml.cli import app


runner = CliRunner()


def test_cli_help_renders():
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "Manage profile-based Docker workspaces" in result.stdout


def test_init_creates_dsml_toml(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init", "--profile", "minimal", "--force"])

    assert result.exit_code == 0
    text = (tmp_path / "dsml.toml").read_text()
    assert "Workspace-local dsml configuration generated by `dsml init`." in text
    assert "Bundled profile name from profiles/*.toml" in text
    assert 'profile = "minimal"' in text
    assert 'mount = "./workspace"' in text
    assert 'image_policy = "auto"' in text
    assert 'root_dir = "/home/jovyan/work"' in text


def test_add_accepts_requirements_file_option(monkeypatch):
    calls = []

    monkeypatch.setattr(cli.runtime, "add", lambda packages, requirements=None: calls.append((packages, requirements)))

    result = runner.invoke(app, ["add", "-r", "requirements.txt"])

    assert result.exit_code == 0
    assert calls == [([], [Path("requirements.txt")])]
