from typer.testing import CliRunner

from dsml.cli import app


runner = CliRunner()


def test_cli_help_renders():
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "Manage profile-based Docker workspaces" in result.stdout


def test_init_creates_dsml_toml(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init", "--profile", "minimal", "--force"])

    assert result.exit_code == 0
    text = (tmp_path / "dsml.toml").read_text()
    assert "Workspace-local dsml configuration generated by `dsml init`." in text
    assert "Bundled profile name from profiles/*.toml" in text
    assert 'profile = "minimal"' in text
    assert 'mount = "./workspace"' in text
    assert 'root_dir = "/home/jovyan/work"' in text
