from pathlib import Path

from typer.testing import CliRunner

from dsml import __version__
from dsml import cli
from dsml.cli import app


runner = CliRunner()


def test_cli_help_renders():
    result = runner.invoke(app, ["--help"])

    assert result.exit_code == 0
    assert "Manage profile-based Docker workspaces" in result.stdout


def test_cli_version_renders():
    result = runner.invoke(app, ["--version"])

    assert result.exit_code == 0
    assert f"dsml-kit {__version__}" in result.stdout


def test_init_creates_dsml_yml(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init", "--profile", "minimal", "--force"])

    assert result.exit_code == 0
    text = (tmp_path / "dsml.yml").read_text()
    assert "Workspace-local dsml configuration generated by `dsml init`." in text
    assert "Bundled profile name from profiles/*.yml" in text
    assert "profile: minimal" in text
    assert "runtime:" in text
    assert "backend: compose" in text
    assert "mount: ./workspace" in text
    assert "image_policy: auto" in text
    assert "image_build:" in text
    assert "dockerfile: images/base/Dockerfile" in text
    assert "root_dir: /home/jovyan/work" in text


def test_add_accepts_requirements_file_option(monkeypatch):
    calls = []

    monkeypatch.setattr(cli.runtime, "add", lambda packages, requirements=None: calls.append((packages, requirements)))

    result = runner.invoke(app, ["add", "-r", "requirements.txt"])

    assert result.exit_code == 0
    assert calls == [([], [Path("requirements.txt")])]


def test_up_accepts_compose_runtime_flags(monkeypatch):
    calls = []

    monkeypatch.setattr(cli.runtime, "up", lambda **kwargs: calls.append(kwargs))

    result = runner.invoke(app, ["up", "--recreate", "--no-wait", "--wait-timeout", "5"])

    assert result.exit_code == 0
    assert calls == [
        {
            "attach": False,
            "build": False,
            "pull": False,
            "dev": False,
            "recreate": True,
            "wait": False,
            "wait_timeout": 5,
        }
    ]


def test_watch_accepts_compose_watch_flags(monkeypatch):
    calls = []

    monkeypatch.setattr(cli.runtime, "watch", lambda **kwargs: calls.append(kwargs))

    result = runner.invoke(app, ["watch", "--dev", "--no-up", "--no-prune", "--quiet"])

    assert result.exit_code == 0
    assert calls == [
        {
            "dev": True,
            "no_up": True,
            "prune": False,
            "quiet": True,
        }
    ]


def test_image_build_accepts_custom_build_options(monkeypatch, tmp_path):
    calls = []
    docker_dir = tmp_path / "docker"
    docker_dir.mkdir()
    (docker_dir / "Dockerfile").write_text("FROM example\n")
    monkeypatch.chdir(tmp_path)

    monkeypatch.setattr(cli.images, "build_image", lambda **kwargs: calls.append(kwargs))

    result = runner.invoke(
        app,
        [
            "image",
            "build",
            "--tag",
            "example:test",
            "--context",
            "docker",
            "--dockerfile",
            "docker/Dockerfile",
            "--target",
            "prod",
            "--build-arg",
            "PYTHON_VERSION=3.12",
        ],
    )

    assert result.exit_code == 0
    assert calls == [
        {
            "tag": "example:test",
            "dev": False,
            "context": Path("docker"),
            "dockerfile": Path("docker/Dockerfile"),
            "target": "prod",
            "build_args": {
                "DSML_REQUIREMENTS": "requirements-base.txt",
                "PYTHON_VERSION": "3.12",
            },
        }
    ]


def test_image_build_rejects_unsupported_python_version(monkeypatch):
    monkeypatch.setattr(cli.images, "build_image", lambda **kwargs: None)

    result = runner.invoke(app, ["image", "build", "--build-arg", "PYTHON_VERSION=2.7"])

    assert result.exit_code == 1
    assert "PYTHON_VERSION" in result.stdout


def test_status_command_renders_backend_status(monkeypatch, tmp_path):
    monkeypatch.setattr(
        cli.runtime,
        "status",
        lambda: cli.runtime.WorkspaceStatus(
            backend="compose",
            project_name="project-test",
            container_name="dsml-project-test",
            image="example:test",
            running=True,
            config_path=tmp_path / "dsml.yml",
            compose_file=tmp_path / ".dsml" / "compose.yaml",
            url="http://127.0.0.1:8888/?token=test",
        ),
    )

    result = runner.invoke(app, ["status"])

    assert result.exit_code == 0
    assert "compose" in result.stdout
    assert "project-test" in result.stdout


def test_compose_debug_commands_call_runtime(monkeypatch):
    calls = []

    monkeypatch.setattr(cli.runtime, "compose_path_for_workspace", lambda: Path(".dsml/compose.yaml"))
    monkeypatch.setattr(cli.runtime, "compose_config", lambda: calls.append("config"))
    monkeypatch.setattr(cli.runtime, "compose_ps", lambda: calls.append("ps"))

    path_result = runner.invoke(app, ["compose", "path"])
    config_result = runner.invoke(app, ["compose", "config"])
    ps_result = runner.invoke(app, ["compose", "ps"])

    assert path_result.exit_code == 0
    assert ".dsml/compose.yaml" in path_result.stdout
    assert config_result.exit_code == 0
    assert ps_result.exit_code == 0
    assert calls == ["config", "ps"]
